### ISSUE TITLE
issue: 개발 환경 구축

### ISSUE THREAD

**Issue by JeongUijeong** [Shimpyo-House/Shimpyo_BE#1]
### Description
> 기획 및 설계를 바탕으로 개발 환경을 구축한다. 

### Todo
- [x] Spring REST Docs 설정
- [x] 각 Entity와 Repository 생성
- [x] GitHub Action CI 도입
