### ISSUE TITLE
issue: 객실 상세 조회 시, 보유 수량 응답

### ISSUE THREAD

**Issue by wocjf0513** [Shimpyo-House/Shimpyo_BE#105]
### Description
같은 디럭스 룸이라도 방 응답 데이터를 여러 개로 보내는 걸 
-> 방 응답 데이터에 보유 수량으로 대채 해, 같은 룸이면 보유 수량을 증가하는 걸로 대체하고자 합니다. 

### Todo
- [ ] 객실 상세 조회 API 수정
- [ ] 방 코드 별 예약 가능한지, 남은 수량이 몇개 인지 조회 API 구현
- [ ] 이에 따른 TEST 수정
