### ISSUE TITLE
issue: 객실 예약 가능 확인 및 선점 API 로직 수정

### ISSUE THREAD

**Issue by jo0oy** [Shimpyo-House/Shimpyo_BE#109]
### Description
> 객실 테이블에 roomCode가 추가되어 roomCode에 따라 예약 가능 여부를 확인하고 
선점 완료시 매칭된 roomId를 응답 바디에 보내도록 합니다.

### Todo
- [x] Request Body에서 roomCode를 받을 수 있도록 수정
- [x] RoomRepository에서 roomCode의 객실 식별자를 조회하는 쿼리 메서드 추가
- [x] 예약 가능 여부 확인 로직 수정
- [x] 예약 선점 로직 수정
- [x] 로직 수정에 따라 Test 추가 작성 또는 수정
