### ISSUE TITLE
issue: docker재설정

### ISSUE THREAD

**Issue by JeongUijeong** [Shimpyo-House/Shimpyo_BE#18]
### Description
> docker를 재설정합니다. 

### Todo
- [x] db port 변경
- [x] yaml 파일 profile 분리
- [x] doker-compose.yaml 수정

### ETC
yaml 파일은 보안 상 github에 올리지는 않습니다.
