### ISSUE TITLE
issue: 주문 목록 조회 기능 개발

### ISSUE THREAD

**Issue by jo0oy** [Shimpyo-House/Shimpyo_BE#29]
### Description
> 전체 주문 목록 조회 기능을 개발합니다.

### Todo
- [x] 전체 주문 목록 조회 기능을 개발합니다.
- [x] 개발한 기능에 대한 Test 코드를 작성하고 정상 동작을 확인합니다.
- [x] Rest Docs를 위한 Test 코드를 작성합니다.
