### ISSUE TITLE
issue: docker-compose 개발 환경 구축

### ISSUE THREAD

**Issue by jo0oy** [Shimpyo-House/Shimpyo_BE#3]
### Description
> docker-compose 로 MariaDB, Redis 개발 환경을 구축한다.

### Todo
- [x] docker-compose.yml 작성
   - [x] MariaDB 
   - [x] Redis
- [x] MariaDB 기본 설정 파일 추가
- [x] Spring Boot Redis 의존성 주입 및 설정 추가
