### ISSUE TITLE
issue: 회원 조회 기능 개발

### ISSUE THREAD

**Issue by JeongUijeong** [Shimpyo-House/Shimpyo_BE#30]
### Description
> 회원 조회 기능을 개발한다. 
- FE 측에서 F5를 누를 시 회원 정보가 사라지기 때문에 회원 조회 API가 필요하다고 요청해주셨습니다. 
- 이에 따라 회원 조회 API를 개발하기로 했습니다. 

### Todo
- [x] 회원 조회 API 개발
- [x] 회원 조회 Service, Controller 테스트 작성
- [x] 회원 조회 API adoc 파일 작성
