### ISSUE TITLE
issue: 상품 이미지 관련 테이블 및 변경 사항 적용

### ISSUE THREAD

**Issue by wocjf0513** [Shimpyo-House/Shimpyo_BE#33]
### Description
> 상품 별 관련 이미지가 있기에 상품 이미지 entity 를 추가하고자 합니다.

### Todo
- [ ] product mapper 변경 
- [ ] 상품 이미지 관련 test 코드 추가 및 변경
- [ ] 상품 이미지 테이블 entity 추가
- [ ] 상품 이미지 repository 추가
