### ISSUE TITLE
issue: 상품 관련 API 만들기 (API 명세서에 맞게)

### ISSUE THREAD

**Issue by wocjf0513** [Shimpyo-House/Shimpyo_BE#4]
### Description
> API 명세서에 적힌 대로 일단 만든 후, OPEN API 관련 응답을 받고 수정 예정

### Todo
- [x] 상품 전체 조회 작성
- [x] 관련 DTO 생성
- [x] 상품 조건 별 조회 (객실까지 조회)
- [x] 관련 DTO 생성
