### ISSUE TITLE
issue: 예약 가능 유효성 검증 및 선점 기능 개발

### ISSUE THREAD

**Issue by jo0oy** [Shimpyo-House/Shimpyo_BE#42]
### Description
> '예약' 페이지로 넘어갈 때 예약이 가능한 객실과 날짜 기간인지 확인하고, 검증이 통과되었을 때 미리 선점하는 기능을 개발합니다. 

### Todo
- [x] 레디스 분산락 Redisson 설정 셋업
- [x] Redisson 분산락을 lock 할 Facade 클래스 추가
- [x] Request/Response DTO 추가
- [x] 기능 관련 서비스 비즈니스 로직 구현
- [x] '예약 가능 유효성 검증 및 선점' API 구현
- [x] 기능 로직에 대한 Test code 작성
