### ISSUE TITLE
issue: 상품 관련 테스트 개발

### ISSUE THREAD

**Issue by wocjf0513** [Shimpyo-House/Shimpyo_BE#43]
### Description
> 실제 배포되기 전에, 관련 기능이 작동하는지 테스트를 개발합니다.

### Todo
- [x] 상품 관련 통합 테스트 개발
- [x] 상품 관련 유닛 테스트 개발
- [ ] 상품 관련 rest docs 작성
