### ISSUE TITLE
issue: 예약 최종 등록 개발

### ISSUE THREAD

**Issue by jo0oy** [Shimpyo-House/Shimpyo_BE#49]
### Description
> 예약하고자 하는 데이터를 최종적으로 검증하고 결제 처리 후 DB에 저장하도록 기능을 구현합니다.

### Todo
- [x] 예약 데이터 최종 검증 로직 구현
- [x] 예약 데이터 DB에 저장 로직 구현
- [x] 예약 결제 및 등록 API 구현
- [x] 구현한 기능에 대한 Test 작성
- [x] Rest Docs를 위한 Test 작성
