### ISSUE TITLE
issue: Open API 활용 기능 개발

### ISSUE THREAD

**Issue by JeongUijeong** [Shimpyo-House/Shimpyo_BE#50]
### Description
> Open API 활용 기능을 개발한다. 
Open API를 활용하여 숙박 상품 데이터를 불러오고, 필요한 부분만 정제하여 DB에 저장하도록 개발합니다. 

### Todo
- [x] OpenAPI에서 가져올 수 있는 정보를 담기 위해 Product 엔터티 수정
- [x] Category 수정
- [x] Area enum 생성
- [x] 관련된 기존 파일 수정
- [x] OpenApiService 구현
