### ISSUE TITLE
issue: 주문/결제 페이지 객실 정보 조회 개발

### ISSUE THREAD

**Issue by jo0oy** [Shimpyo-House/Shimpyo_BE#92]
### Description
> 주문/결제 페이지에서 주문 상품 목록 리스트를 위한 객실 정보 조회 API를 개발합니다.

### Todo
- [x] 객실 정보 조회 서비스 로직 구현
- [x] 객실 정보 조회 API 구현
- [x] 구현한 기능에 대한 Unit Test 작성 및 확인
- [x] Rest Docs를 위한 Test 작성
