### ISSUE TITLE
issue: 예약 API Request Body 및 서비스 로직 수정

### ISSUE THREAD

**Issue by jo0oy** [Shimpyo-House/Shimpyo_BE#97]
### Description
> 예약 API에서 불필요하게 받고 있던 Request Body를 수정합니다. 
Request Body 변경으로 인해 예약을 저장하고 Response를 반환하는 서비스 로직을 수정합니다.

### Todo
- [x] 예약 API의 Request DTO 불필요한 필드 제거
- [x] 예약 서비스 로직에서 마지막 응답을 보내기 위한 로직 수정
- [x] 리팩토링으로 영향 받은 Test 수정 업데이트
